### ISSUE TITLE
Make API endpoints return the correct status code when returning an error

### ISSUE THREAD

**Issue by QuantumToasted** [alanedwardes/Estranged.Lfs#13]
Hi,

I am using this library with the [Estranged.Lfs.Api](https://github.com/alanedwardes/Estranged.Lfs/tree/master/src/Estranged.Lfs.Api) and [Estranged.Lfs.Authenticator.GitHub](https://github.com/alanedwardes/Estranged.Lfs/tree/master/src/Estranged.Lfs.Authenticator.GitHub) addons.

Not sure if this is an issue on my end, but looking at source code and other examples, I have built my own `IBlobAdapter`, which will return errors in certain circumstances. Testing this in Postman locally, my `error` object is populated and `code` is set, but the status code returned by the server is still 200 OK. It would be nice to set the status code in the response when handled internally by the library, as as far as I'm aware I do not have control over this.
![image](https://user-images.githubusercontent.com/30324210/232177632-9924430e-7d52-4546-82c3-23627d8da091.png)

**Comment by alanedwardes** [comment]
Hi Daniel,

This is part of the Git LFS spec: https://github.com/git-lfs/git-lfs/blob/main/docs/api/batch.md

> If there are problems accessing individual objects, servers should continue to return a 200 status code, and provide per-object errors. Here is an example:

That’s because it’s a batch response, and the response could be partial. If this library did anything different, LFS clients would break as it’s no longer following the spec.

Alan

**Comment by QuantumToasted** [comment]
Makes sense, I forgot about that quirk of the API spec - that it supports actually processing multiple files at the same time. Thanks!
