### ISSUE TITLE
Regarding the magic in git-lfs.yaml 

### ISSUE THREAD

**Issue by jdannenbring** [alanedwardes/Estranged.Lfs#2]
I previously tried using the *magic link* from [your blog](https://alanedwardes.com/blog/posts/serverless-git-lfs-for-game-dev/) to set up the stack. Since I'm in us-west I thought changing the console region would do the trick, but not quite.

After getting the manual setup to work (thanks for the git lfs version hint!), I looked at the git-lfs.yaml and am seeing that the line:

`Code:
                S3Bucket: !Sub 'ae-infrastructure-${AWS::Region}'
                S3Key: git-lfs/git-lfs-lambda.zip`

Should actually hardcode the region in this case (as its pointing to the packaged version of this codebase you've kindly uploaded to eu-west-1). So instead the code should be:

`Code:
                S3Bucket: !Sub 'ae-infrastructure-eu-west-1.s3.amazonaws.com'
                S3Key: git-lfs/git-lfs-lambda.zip`

**Comment by alanedwardes** [comment]
Hi,

When I try this, CloudFormation complains about the code bucket being in a different region:

![image](https://user-images.githubusercontent.com/110954/46178211-d7c5df00-c2ad-11e8-9264-b94ce70d834b.png)

```
Error occurred while GetObject. S3 Error Code: AuthorizationHeaderMalformed. S3 Error Message: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'eu-west-1' (Service: AWSLambda; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 53249a0d-c2a5-11e8-8673-e93cc8a11d3f)
```

Did you change this and see it working?

Cheers

**Comment by jdannenbring** [comment]
I hadn't tried it till now. Looks like the issue is my lambda function on us-west cannot access your 'ae-infrastructure-eu-west-1' bucket (even though its publicly downloadable).

When I make a bucket and put the **git-lfs-lambda.zip** there, then the code in the yaml works:
`Code:
                S3Bucket: !Sub 'cf-templates-124hcfrvf3ol2-${AWS::Region}'
                S3Key: git-lfs-lambda.zip`

**Comment by alanedwardes** [comment]
No - this is a limitation of AWS Lambda. Since I don't want to maintain a bucket in each region, the script will only support `eu-west-1` for now - so hardcoding that region or keeping it as `${AWS::Region}` is functionally the same :)

**Comment by jdannenbring** [comment]
I see, understood. Thanks!
