### ISSUE TITLE
git lfs prune --verify-remote behave unexpectedly

### ISSUE THREAD

**Issue by elfmimi** [alanedwardes/Estranged.Lfs#3]
`git lfs prune --verify-remote` behave unexpectedly when combined with Estranged.Lfs .
It seems Estranged.Lfs always responds to inquiries with a positive answer that is as if "the file in question does exists" unconditionally.

**Comment by alanedwardes** [comment]
Hi,

Thanks for the report! Can you include some anomyised logs of the request/responses with the environment variable `GIT_TRACE=1`? I'm looking to track down the specific requests that respond positively when they shouldn't.

Thanks,
Alan

**Comment by elfmimi** [comment]
Here you are. I've also added GIT_CURL_VERBOSE=1 to see headers and contents of the POST request.

[log-with-empty-bucket.txt](https://github.com/alanedwardes/Estranged.Lfs/files/4773896/log-with-empty-bucket.txt)
The lambda is connected to a newly created empty bucket. So there exist no object to download at all.

[log-with-server-down.txt](https://github.com/alanedwardes/Estranged.Lfs/files/4773898/log-with-server-down.txt)
Throttling the lambda with setting concurrency down to zero, the api returns an error. but it is being treated correctly as negative, no file exists, answer.

**Comment by alanedwardes** [comment]
Thanks for the additional information - it looks like this particular git lfs operation doesn't follow the signed URL, so it doesn't actually verify whether it can get the data.

I'll count this as a feature request, since it will require the batch download endpoint to ping S3 for each object it's asked to return to confirm it exists - I'll try to get to it within the next few weeks.

Thanks,
Alan

**Comment by alanedwardes** [comment]
For reference - I have started a new branch for the changes around this feature: https://github.com/alanedwardes/Estranged.Lfs/tree/fetch-object-metadata

**Comment by alanedwardes** [comment]
This was addressed with version 3.0.0 - Estranged.Lfs now makes HEAD requests in parallel to S3 to verify all requested objects exist. https://github.com/alanedwardes/Estranged.Lfs/releases

**Comment by elfmimi** [comment]
I wasn't expecting this would be solved in such a short time.
Thank you very much. @alanedwardes 
note: I purchased act.II as a sign of appreciation.
