### ISSUE TITLE
Support for Azure blob storage

### ISSUE THREAD

**Issue by Stephanvs** [alanedwardes/Estranged.Lfs#6]
Hi,

Thanks, I was looking for a self-hosted alternative to GitHub's LFS storage because I'm currently blasting through my LFS storage limit's. I came across your library and blog posts which is exactly what I was looking for.

The thing is I would like to store my LFS files in the Azure cloud, so I decided to code support for azure blob storage (basically the Azure equivalent of S3).

I'll open a PR once I'm done, so you can take a look.

Let me know what you think.

Stephanvs

**Comment by alanedwardes** [comment]
Hi Stephan,

An Azure adapter would be fantastic! I intended to add one eventually, but I work more with AWS than Azure and just didn't get around to doing it (and also wouldn't be able to test it as well as the S3 adapter, considering I use that nearly every day!).

Let me know when you have something to review,

Alan

**Comment by Stephanvs** [comment]
Thanks so much for merging my PR 💯

**Comment by alanedwardes** [comment]
Thanks for your contribution :) I pushed verison 3.1.0 of the packages, they'll be indexed shortly but are ready for use:
- https://www.nuget.org/packages/Estranged.Lfs.Adapter.Azure.Blob/3.1.0
- https://www.nuget.org/packages/Estranged.Lfs.Adapter.S3/3.1.0
- https://www.nuget.org/packages/Estranged.Lfs.Api/3.1.0
- https://www.nuget.org/packages/Estranged.Lfs.Authenticator.BitBucket/3.1.0
- https://www.nuget.org/packages/Estranged.Lfs.Authenticator.GitHub/3.1.0
- https://www.nuget.org/packages/Estranged.Lfs.Data/3.1.0
